import type { PlayerRosterItem } from '@/types/api'

export const PLACEHOLDER_PLAYER_ROSTER: PlayerRosterItem[] = [
  {
    id: 1,
    nickname: 'Pulse',
    race: 'P',
    tier: 'S',
    currentMmr: 1620,
    wins: 20,
    losses: 9,
    games: 29,
  },
  {
    id: 2,
    nickname: 'WarpNode',
    race: 'T',
    tier: 'A+',
    currentMmr: 1540,
    wins: 18,
    losses: 11,
    games: 29,
  },
  {
    id: 3,
    nickname: 'SwarmCore',
    race: 'Z',
    tier: 'A-',
    currentMmr: 1495,
    wins: 16,
    losses: 13,
    games: 29,
  },
  {
    id: 4,
    nickname: 'NexusFox',
    race: 'P',
    tier: 'B+',
    currentMmr: 1450,
    wins: 14,
    losses: 14,
    games: 28,
  },
  {
    id: 5,
    nickname: 'SiegeRain',
    race: 'T',
    tier: 'B',
    currentMmr: 1410,
    wins: 12,
    losses: 15,
    games: 27,
  },
  {
    id: 6,
    nickname: 'LarvaKing',
    race: 'Z',
    tier: 'UNASSIGNED',
    currentMmr: 1390,
    wins: 10,
    losses: 16,
    games: 26,
  },
]
