ALTER TABLE matches
    ADD COLUMN IF NOT EXISTS source VARCHAR(20);

UPDATE matches
SET source = COALESCE(source, 'BALANCED');

ALTER TABLE matches
    ALTER COLUMN source SET NOT NULL;

ALTER TABLE matches
    ALTER COLUMN source SET DEFAULT 'BALANCED';

ALTER TABLE matches
    ADD COLUMN IF NOT EXISTS note VARCHAR(255);
