ALTER TABLE players
    ADD COLUMN IF NOT EXISTS dormant_since TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS returned_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS return_boost_games_remaining INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS return_boost_multiplier DOUBLE PRECISION NOT NULL DEFAULT 1.0;
